config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "gossips#index"
  resources :gossips do
    resources :comments
  end
  resources :sessions, only: [:new, :create, :destroy]
  # get "/gossips", to: "gossips#index"
  # get "/gossips/:id", to: "gossips#show"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  include Visible

  belongs_to :gossip
end

app/models/concerns/visible.rb
module Visible
    extend ActiveSupport::Concern

    VALID_STATUSES = ['public', 'private', 'archived']
  
    included do
      validates :status, inclusion: { in: VALID_STATUSES }
    end  

    class_methods do
        def public_count
            where(status: 'public').count
        end
    end

    def archived?
        status == 'archived'
    end
end

app/models/gossip.rb
class Gossip < ApplicationRecord
    include Visible

    has_many :comments
  
    validates :title, presence: true
    validates :body, presence: true, length: { minimum: 10 }
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    http_basic_authenticate_with name: "dhh", password: "secret", only: :destroy

    def create
        @gossip = Gossip.find(params[:gossip_id])
        @comment = @gossip.comments.create(comment_params)

        redirect_to gossip_path(@gossip)
    end

    def destroy
        @gossip = Gossip.find(params[:gossip_id])
        @comment = @gossip.comments.find(params[:id])
        @comment.destroy
        redirect_to gossip_path(@gossip), status: :see_other
    end

    private
    def comment_params
        params.require(:comment).permit(:commenter, :body, :status)
    end
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController

  http_basic_authenticate_with name: "dhh", password: "secret", except: [:index, :show]

  def index
    @gossips = Gossip.all
  end

  def show
    @gossip = Gossip.find(params[:id])
  end

  def new
    @gossip = Gossip.new
  end

  def create
    @gossip = Gossip.new(gossip_params)
    if @gossip.save
      redirect_to @gossip
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @gossip = Gossip.find(params[:id])
  end

  def update
    @gossip = Gossip.find(params[:id])

    if @gossip.update(gossip_params)
      redirect_to @gossip
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @gossip = Gossip.find(params[:id])
    @gossip.destroy

    redirect_to root_path, status: :see_other
  end

  private
  def gossip_params
    params.require(:gossip).permit(:title, :body, :status)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    # cherche s'il existe un utilisateur en base avec l’e-mail
    user = User.find_by(email: email_dans_ton_params)
  
    # on vérifie si l'utilisateur existe bien ET si on arrive à l'authentifier (méthode bcrypt) avec le mot de passe 
    if user && user.authenticate(password_dans_ton_params)
      session[:user_id] = user.id
      # redirige où tu veux, avec un flash ou pas
  
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    session.delete(:user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/comments/_comment.html.erb
<% unless comment.archived? %>
    <p>
        <strong>Commenter:</strong>
        <%= comment.commenter %>
    </p>

    <p>
        <strong>Comment:</strong>
        <%= comment.body %>
    </p>

    <p>
        <%= link_to "Destroy Comment", [comment.gossip, comment], data: {
                  turbo_method: :delete,
                  turbo_confirm: "Are you sure?"
                } %>
    </p>
<% end %>

app/views/comments/_form.html.erb
<%= form_with model: [ @gossip, @gossip.comments.build ] do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
  <p>
    <%= form.label :status %><br>
    <%= form.select :status, ['public', 'private', 'archived'], selected: 'public' %>
  </p>
<% end %>

app/views/gossips/_form.html.erb
<%= form_with model: gossip do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% gossip.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %><br>
    <% gossip.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
  <div>
    <%= form.label :status %><br>
    <%= form.select :status, ['public', 'private', 'archived'], selected: 'public' %>
  </div>
<% end %>

app/views/gossips/edit.html.erb
<h1>Edit Gossip</h1>

<%= render "form", gossip: @gossip %>

app/views/gossips/index.html.erb
<h1>Gossips</h1>

Our blog has <%= Gossip.public_count %> gossips and counting!

<ul>
    <% @gossips.each do |gossip |%>
        <% unless gossip.archived? %>
            <li>
                <%= link_to gossip.title, gossip %>
            </li>
        <% end %>
    <% end %>
</ul>

<%= link_to "New Gossip", new_gossip_path %>

app/views/gossips/new.html.erb
<h1>New Gossip</h1>

<%= render "form", gossip: @gossip %>

app/views/gossips/show.html.erb
<h1> <%= @gossip.title %> </h1>

<p> <%= @gossip.body %> </p>

<ul>
    <li><%= link_to "Edit", edit_gossip_path(@gossip) %></li>
    <li> <%= link_to "Destroy", gossip_path(@gossip), data: {
        turbo_method: :delete,
        turbo_confirm: "Are you sure?"
        } %> </li>
</ul>

<h2>Comments</h2>
<%= render @gossip.comments %>

<h2>Add a comment:</h2>
<%= render 'comments/form' %>

<%= link_to "Retour à l'accueil", root_path, class: "btn btn-primary" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
  <meta charset="utf-8">
  <title>TheGossipProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
</head>
<body>

  <header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="/">Index</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="nav-item nav-link active" href="/gossips/new">Balance un nouveau Gossip man!</a>
          
        </div>
      </div>
      <%= link_to "Se déconnecter", session_path(session.id), method: :delete %>
    </nav>
  </header>


  <%= yield %>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
</body>
</html>